import { useState, useRef, useEffect } from "react";

// ═══════════════════════════════════════════════════════════════
// WDC AI TRAVEL — FULL APP (Merged: original form + redesigned results + theme toggle + chat)
// ═══════════════════════════════════════════════════════════════

// ── CONSTANTS ──
const AIRPORTS=[{code:"GVA",name:"Genève-Cointrin"},{code:"ZRH",name:"Zurich"},{code:"MXP",name:"Milan Malpensa"},{code:"CDG",name:"Paris CDG"},{code:"LHR",name:"Londres Heathrow"},{code:"BCN",name:"Barcelone"},{code:"FCO",name:"Rome Fiumicino"},{code:"AMS",name:"Amsterdam"},{code:"MAD",name:"Madrid"},{code:"DXB",name:"Dubai"},{code:"JFK",name:"New York JFK"},{code:"LAX",name:"Los Angeles"},{code:"BKK",name:"Bangkok"},{code:"SIN",name:"Singapour"},{code:"OTHER",name:"Autre"}];
const VIBES=[{id:"beach",label:"🏖 Plage & Mer"},{id:"city",label:"🏙 Ville & Culture"},{id:"nature",label:"🌿 Nature & Montagne"},{id:"party",label:"🎉 Fête & Nightlife"},{id:"gastro",label:"🍽 Gastronomie"},{id:"spa",label:"💆 Détente & Spa"},{id:"adventure",label:"🏄 Aventure & Sport"},{id:"romance",label:"💑 Romance"},{id:"luxury",label:"💎 Luxe & VIP"},{id:"family",label:"👨‍👩‍👧 Famille"}];
const ACTIVITIES=[{id:"surf",label:"Surf"},{id:"golf",label:"Golf"},{id:"diving",label:"Plongée"},{id:"hiking",label:"Randonnée"},{id:"restaurants",label:"Restos étoilés"},{id:"shopping",label:"Shopping"},{id:"clubs",label:"Clubs & Bars"},{id:"yoga",label:"Yoga & Wellness"},{id:"museums",label:"Musées"},{id:"sailing",label:"Voile & Bateau"},{id:"skiing",label:"Ski"},{id:"snorkeling",label:"Snorkeling"},{id:"tennis",label:"Tennis"},{id:"safari",label:"Safari"}];
const LOYALTY=[{id:"revolut_ultra",short:"Revolut Ultra"},{id:"amex_ch",short:"Amex"},{id:"ubs_infinite",short:"UBS Visa"},{id:"miles_more",short:"Miles & More"},{id:"marriott_bonvoy",short:"Marriott Bonvoy"},{id:"hilton_honors",short:"Hilton Honors"},{id:"world_of_hyatt",short:"World of Hyatt"},{id:"diners_club",short:"Diners Club"}];
const POINTS_MARKS=[0,5000,10000,15000,20000,25000,30000,40000,50000,75000,100000];
const BAGGAGE_OPTIONS=[{id:"no_pref",label:"Pas de préférence"},{id:"cabin_only",label:"Cabine seulement"},{id:"1_checked_23",label:"1 bagage 23 kg"},{id:"2_checked_23",label:"2 bagages 23 kg"},{id:"sport",label:"Bagage sport / golf"}];
const TIPS=["Recherche des vols sur Kayak et Google Flights...","Consultation de Skyscanner et Momondo...","Vérification des hôtels sur Booking.com...","Comparaison sur Airbnb et Hotels.com...","Calcul des 3 scénarios de classe...","Conversion des prix en CHF...","Analyse météo à destination...","Finalisation de la recommandation..."];

// ── THEMES ──
const DARK={bg:"#0a0a0a",card:"#141414",card2:"#1c1c1c",input:"#202020",border:"#2a2218",borderH:"#444",text:"#f5f0e8",muted:"#999",faint:"#444",gold:"#c9a96e",goldD:"#a07840",goldBg:"rgba(201,169,110,0.06)",goldBg2:"rgba(201,169,110,0.12)",green:"#22c55e",red:"#ef4444",blue:"#5b9bd5"};
const LIGHT={bg:"#f5f3ef",card:"#ffffff",card2:"#f0ede7",input:"#faf9f7",border:"#e0dcd4",borderH:"#ccc",text:"#1a1a1a",muted:"#6a6560",faint:"#ccc",gold:"#a6872f",goldD:"#8a7535",goldBg:"rgba(166,135,47,0.06)",goldBg2:"rgba(166,135,47,0.12)",green:"#3a8f4a",red:"#c94444",blue:"#3a7abf"};
const FN="'DM Sans','Helvetica Neue',system-ui,sans-serif";
const MN="'JetBrains Mono','SF Mono',monospace";

// ── UTILITIES ──
function clean(text){if(!text)return"";const lines=text.replace(/[—–]/g," - ").split("\n");const out=[];for(const line of lines){const t=line.trim();const prev=out.length>0?out[out.length-1]:null;if(prev!==null&&!prev.trim().startsWith("|")&&!prev.trim().startsWith("#")&&(/^[,;]/.test(t)||/^\.\s/.test(t)||/^\.$/.test(t)||(t.length>0&&t.length<=4&&!/^[|#\-*✅•\d]/.test(t)&&t!==""))){out[out.length-1]=out[out.length-1].trimEnd()+(t.startsWith(",")||t.startsWith(".")||t.startsWith(";")?"":" ")+t;}else{out.push(line);}}return out.join("\n");}
function renderInline(s){return(s||"").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\*(.+?)\*/g,"<em>$1</em>").replace(/\[([^\]]+)\]\(([^)]+)\)/g,`<a href="$2" target="_blank" rel="noopener" style="color:inherit;text-decoration:underline">$1 ↗</a>`);}
function extractImages(lines){for(const l of lines){const m=l.match(/^IMAGES:\s*(.+)/i);if(m)return m[1].split("|").map(u=>u.trim()).filter(u=>u.startsWith("http"));}return[];}
function parseSections(text){const lines=clean(text).split("\n");const sections=[];let cur=null;for(const l of lines){const h2=l.match(/^## (.+)/);if(h2){if(cur)sections.push(cur);cur={title:h2[1].trim(),lines:[]};}else if(cur)cur.lines.push(l);}if(cur)sections.push(cur);return sections;}
function parseHotelBlocks(lines){const blocks=[];let cur=null;for(const l of lines){const h3=l.match(/^### (.+)/);if(h3){if(cur)blocks.push(cur);const name=h3[1].trim();const isHeader=/\(\d+\s*nuits?\)/i.test(name)||/^[A-Z\s\-,]{4,}$/.test(name);cur={name,lines:[],isHeader};}else if(cur)cur.lines.push(l);}if(cur)blocks.push(cur);return blocks;}
function parseTable(lines){const data={};for(const l of lines){if(l.startsWith("|")&&!l.match(/^[\|\s:\-]+$/)){const cells=l.split("|").slice(1,-1).map(c=>c.trim());if(cells.length>=2&&cells[0]&&cells[1]){const key=cells[0].toLowerCase().replace(/[éèê]/g,"e").replace(/[àâ]/g,"a").replace(/[îï]/g,"i").replace(/\s+/g,"_").replace(/[^a-z_\/]/g,"");data[key]=cells[1];}}}return data;}
function titleParts(t){const m=t.match(/^([\u{1F300}-\u{1FFFF}][\uFE0F\u200D]*)+\s*/u);if(m)return{icon:m[0].trim(),label:t.slice(m[0].length).trim()};return{icon:"",label:t};}
const fmt=n=>n?.toString().replace(/\B(?=(\d{3})+(?!\d))/g,"'")||"0";

// ── SHARED UI ──
function Sec({icon,title,children,t,defaultOpen=false,accent=false}){const[o,setO]=useState(defaultOpen);const{icon:ti,label}=typeof title==="string"?titleParts(title):{icon:"",label:title};return(<div style={{background:t.card,border:`1px solid ${accent?t.gold:t.border}`,borderRadius:14,marginBottom:10,overflow:"hidden"}}><button onClick={()=>setO(x=>!x)} style={{width:"100%",display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 20px",background:"none",border:"none",cursor:"pointer",borderBottom:o?`1px solid ${t.border}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:10}}>{(icon||ti)&&<span style={{fontSize:16}}>{icon||ti}</span>}<span style={{fontSize:13,fontWeight:700,color:accent?t.gold:t.text,fontFamily:FN}}>{label}</span></div><span style={{color:t.muted,fontSize:18,fontWeight:300}}>{o?"−":"+"}</span></button>{o&&<div style={{padding:"18px 22px"}}>{children}</div>}</div>);}
function Tag({children,color,t}){const c=color||t.gold;return<span style={{display:"inline-flex",alignItems:"center",gap:4,fontSize:11,fontWeight:500,color:c,background:`${c}15`,border:`1px solid ${c}30`,borderRadius:20,padding:"2px 10px",fontFamily:FN}}>{children}</span>;}
function Lbl({children,t}){return<div style={{fontSize:10,fontWeight:600,letterSpacing:"0.1em",color:t.muted,marginBottom:6,textTransform:"uppercase",fontFamily:FN}}>{children}</div>;}
function ChipBtn({label,selected,onClick,t}){return<button type="button" onClick={onClick} style={{padding:"7px 15px",borderRadius:20,border:`1px solid ${selected?t.gold:t.border}`,background:selected?t.goldBg2:"transparent",color:selected?t.gold:t.muted,fontSize:12,cursor:"pointer",fontFamily:FN,whiteSpace:"nowrap"}}>{label}</button>;}

// ── PROSE BLOCK ──
function ProseBlock({lines,t}){const cleaned=clean(lines.join("\n")).split("\n").filter(l=>{const s=l.trim();return s&&s!=="|"&&!/^\|[\s:\-|]+\|$/.test(s)&&!/^IMAGES:/i.test(s)&&!/^#{1,4}\s/.test(s);});const out=[];let tbl=[],lst=[];
const flushList=()=>{if(!lst.length)return;out.push(<ul key={`l${out.length}`} style={{margin:"0.4rem 0",paddingLeft:"1.4rem"}}>{lst.map((x,i)=><li key={i} style={{margin:"0.2rem 0",lineHeight:1.65,fontSize:14,color:t.muted}} dangerouslySetInnerHTML={{__html:renderInline(x)}}/>)}</ul>);lst=[];};
const flushTable=()=>{if(!tbl.length)return;const rows=tbl.filter(r=>!/^\|[\s:\-|]+\|$/.test(r.trim()));if(!rows.length){tbl=[];return;}const parse=r=>r.split("|").slice(1,-1).map(c=>c.trim());const[head,...body]=rows;out.push(<div key={`t${out.length}`} style={{overflowX:"auto",margin:"1rem 0",borderRadius:10,overflow:"hidden",border:`1px solid ${t.border}`}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{background:t.card2}}>{parse(head).map((h,i)=><th key={i} style={{padding:"11px 16px",textAlign:"left",fontWeight:700,color:t.gold,fontSize:10,letterSpacing:"0.1em",textTransform:"uppercase",borderBottom:`2px solid ${t.border}`}} dangerouslySetInnerHTML={{__html:renderInline(h)}}/>)}</tr></thead><tbody>{body.map((r,i)=>{const cells=parse(r);return<tr key={i} style={{background:i%2===0?t.card:t.card2,borderBottom:`1px solid ${t.border}`}}>{cells.map((c,j)=><td key={j} style={{padding:"11px 16px",fontSize:13,color:j===0?t.text:t.muted,fontWeight:j===0?600:400}} dangerouslySetInnerHTML={{__html:renderInline(c)}}/>)}</tr>;})}</tbody></table></div>);tbl=[];};
for(let i=0;i<cleaned.length;i++){const l=cleaned[i];if(l.startsWith("|")){flushList();tbl.push(l);continue;}flushTable();if(/^[-*•] /.test(l)){lst.push(l.replace(/^[-*•] /,""));}else if(/^---+$/.test(l.trim())){flushList();out.push(<hr key={i} style={{border:"none",borderTop:`1px solid ${t.border}`,margin:"1rem 0"}}/>);}else if(l.trim()===""){flushList();}else{flushList();const isH=l.trim().startsWith("**")&&l.trim().endsWith("**");out.push(<p key={i} style={{margin:"0 0 8px",lineHeight:1.75,fontSize:14,color:isH?t.text:t.muted,fontWeight:isH?600:400}} dangerouslySetInnerHTML={{__html:renderInline(l)}}/>);}}flushList();flushTable();return<>{out}</>;}

// ── PHOTO GRID ──
function PhotoGrid({urls,t}){const[failed,setFailed]=useState({});const[lb,setLb]=useState(null);const valid=(urls||[]).filter((_,i)=>!failed[i]);if(!urls||!urls.length||!valid.length)return(<div style={{height:180,background:`linear-gradient(135deg,#1a1f3c 0%,#0f3460 50%,#1a1f3c 100%)`,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><div style={{fontSize:40,marginBottom:8,opacity:0.6}}>🏨</div><div style={{color:"rgba(255,255,255,0.5)",fontSize:12}}>Photos non disponibles</div></div>);
return(<><div style={{display:"grid",gridTemplateColumns:"1.4fr 1fr",gridTemplateRows:"140px 140px",gap:3,overflow:"hidden",cursor:"zoom-in"}} onClick={()=>setLb(0)}><div style={{gridRow:"1/3",overflow:"hidden"}}><img src={valid[0]} alt="" referrerPolicy="no-referrer" onError={()=>setFailed(f=>({...f,[0]:true}))} style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/></div>{[1,2,3,4].map(i=>valid[i]?<div key={i} style={{overflow:"hidden",position:"relative"}}><img src={valid[i]} alt="" referrerPolicy="no-referrer" onError={()=>setFailed(f=>({...f,[i]:true}))} style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/>{i===4&&valid.length>5&&<div style={{position:"absolute",inset:0,background:"rgba(0,0,0,0.55)",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontSize:13,fontWeight:700}}>+{valid.length-4}</div>}</div>:<div key={i} style={{background:t.card2}}/>)}</div>{lb!==null&&<div onClick={()=>setLb(null)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.96)",zIndex:9999,display:"flex",alignItems:"center",justifyContent:"center"}}><img src={valid[lb]} alt="" style={{maxWidth:"90vw",maxHeight:"85vh",objectFit:"contain",borderRadius:8}} onClick={e=>e.stopPropagation()}/><button onClick={()=>setLb(null)} style={{position:"absolute",top:20,right:24,background:"rgba(255,255,255,0.1)",border:"none",color:"#fff",width:36,height:36,borderRadius:"50%",cursor:"pointer",fontSize:20}}>×</button></div>}</>);}

// ═══════════════════════════════════════════════════════════════
// RESULT DISPLAY COMPONENTS (redesigned)
// ═══════════════════════════════════════════════════════════════

function RecapDisplay({lines,activeClass,prices,t}){const all=clean(lines.join(" "));const destM=all.match(/(?:Destination[s]?[:\s]+|vers?\s+)([A-ZÀ-Ÿa-zà-ÿ\s,→]+?)(?:\s*\||\s*Dates|\s*Durée|\s*\d{1,2})/i);const dest=destM?destM[1].trim().replace(/\s*-\s*$/,""):null;const nightsM=all.match(/(\d+)\s*nuits?/i);const nights=nightsM?nightsM[1]:null;const travM=all.match(/(\d+)\s*(?:personne|voyageur)/i);const travelers=travM?travM[1]:null;const classPrice=activeClass==="business"?prices.business:activeClass==="mixte"?prices.mixte:prices.eco;const classEmoji=activeClass==="business"?"💺":activeClass==="mixte"?"🔀":"🪑";const classLabel=activeClass==="business"?"Full Business":activeClass==="mixte"?"Mixte":"Économie";
return(<div>{dest&&<div style={{marginBottom:20}}><div style={{fontSize:26,fontWeight:900,color:t.text,letterSpacing:"-0.02em",lineHeight:1.1,fontFamily:FN}}>{dest}</div></div>}<div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:22}}>{classPrice&&<div style={{flex:1,minWidth:120,background:t.goldBg2,border:`2px solid ${t.gold}`,borderRadius:12,padding:"16px 14px",textAlign:"center"}}><div style={{fontSize:10,color:t.gold,fontWeight:700,letterSpacing:"0.1em",marginBottom:6}}>{classEmoji} {classLabel.toUpperCase()}</div><div style={{fontSize:28,fontWeight:900,color:t.gold,fontFamily:MN}}>{fmt(parseInt((classPrice||"0").replace(/\s/g,"")))}</div><div style={{fontSize:11,color:t.goldD,marginTop:3}}>CHF total</div></div>}{[nights&&{icon:"🌙",value:nights,label:"nuits"},travelers&&{icon:"👤",value:travelers,label:travelers==="1"?"voyageur":"voyageurs"}].filter(Boolean).map((s,i)=><div key={i} style={{flex:1,minWidth:90,background:t.card2,border:`1px solid ${t.border}`,borderRadius:12,padding:"16px 14px",textAlign:"center"}}><div style={{fontSize:22,marginBottom:6}}>{s.icon}</div><div style={{fontSize:22,fontWeight:900,color:t.text,fontFamily:FN}}>{s.value}</div><div style={{fontSize:11,color:t.muted,marginTop:3}}>{s.label}</div></div>)}</div><ProseBlock lines={lines.filter(l=>{const s=l.trim();return s&&s!=="|"&&!/^\|[\s:\-|]+\|$/.test(s)&&!/^IMAGES:/i.test(s)&&!/^#{1,4}\s/.test(s);})} t={t}/></div>);}

function FlightDisplay({lines,activeClass,setActiveClass,prices,t}){const legs=[];let cur=null;for(const l of lines){const h3=l.match(/^### (.+)/);const bold=l.match(/^\*\*(LEG|Vol|Leg)\s*\d+[^*]*\*\*/i);if(h3||bold){if(cur)legs.push(cur);cur={title:(h3?h3[1]:l.replace(/\*\*/g,"")).trim(),lines:[]};}else if(cur)cur.lines.push(l);}if(cur)legs.push(cur);
return(<div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",borderRadius:12,overflow:"hidden",border:`1px solid ${t.border}`,marginBottom:20}}>{[{id:"business",emoji:"💺",label:"Full Business",price:prices.business},{id:"mixte",emoji:"🔀",label:"Mixte",price:prices.mixte},{id:"eco",emoji:"🪑",label:"Économie",price:prices.eco}].map((c,i)=><button key={c.id} onClick={()=>setActiveClass(c.id)} style={{padding:"14px 8px",textAlign:"center",background:activeClass===c.id?t.goldBg2:t.card2,color:activeClass===c.id?t.gold:t.muted,border:"none",borderBottom:activeClass===c.id?`2px solid ${t.gold}`:"2px solid transparent",borderLeft:i>0?`1px solid ${t.border}`:"none",cursor:"pointer",fontFamily:FN,transition:"all 0.2s"}}><div style={{fontSize:12,fontWeight:700}}>{c.emoji} {c.label}</div>{c.price&&<div style={{fontSize:17,fontWeight:900,marginTop:3,fontFamily:MN}}>{fmt(parseInt((c.price||"0").replace(/\s/g,"")))} CHF</div>}</button>)}</div>{legs.length>1?legs.map((leg,i)=><div key={i} style={{background:t.card2,border:`1px solid ${t.border}`,borderRadius:12,marginBottom:8,overflow:"hidden"}}><div style={{padding:"12px 18px",borderBottom:`1px solid ${t.border}`,background:t.goldBg}}><span style={{fontSize:11,fontWeight:800,color:t.gold,letterSpacing:"0.08em",fontFamily:FN}}>{leg.title}</span></div><div style={{padding:"16px 18px"}}><ProseBlock lines={leg.lines} t={t}/></div></div>):<ProseBlock lines={lines} t={t}/>}</div>);}

function HotelCard({name,lines,t}){const[open,setOpen]=useState(true);const images=extractImages(lines);const td=parseTable(lines);const rating=(td["note"]||"").match(/(\d+\.?\d*)/)?.[1]||null;const stars=(td["etoiles"]||"").replace(/[^★]/g,"").length||null;const zone=td["zone"]||td["emplacement"]||null;const room=td["chambre"]||null;const amenities=(td["equipements"]||"").split(",").map(s=>s.trim()).filter(s=>s&&s.length>1).slice(0,8);const priceNight=(td["prix/nuit"]||td["prix_nuit"]||"").match(/(\d[\d\s]+)/)?.[1]?.replace(/\s/g,"");const priceTotal=(td["prix_total"]||td["prix total"]||"").match(/(\d[\d\s]+)/)?.[1]?.replace(/\s/g,"");let bookingLink=null;const allText=lines.join(" ");const linkM=allText.match(/\[(?:Booking|Réserver)[^\]]*\]\(([^)]+)\)/i);if(linkM)bookingLink=linkM[1];const proseLines=lines.filter(l=>{const s=l.trim();return s&&!/^IMAGES:/i.test(s)&&!/^#{1,4}\s/.test(s)&&!/^\|/.test(s)&&!/^(https?:)?\/\//.test(s)&&!/^\[Site officiel\]|^\[Booking/.test(s);}).slice(0,4);const chips=[...amenities.map(a=>({label:a})),room&&{label:room.split(",")[0].trim()}].filter(Boolean);const rN=parseFloat(rating||"0");const rC=rN>=9?"#16a34a":rN>=8?"#1d8348":"#2e7d32";
return(<div style={{background:t.card2,border:`1px solid ${t.border}`,borderRadius:14,marginBottom:14,overflow:"hidden"}}><button onClick={()=>setOpen(o=>!o)} style={{width:"100%",display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 18px",background:"none",border:"none",cursor:"pointer",borderBottom:open?`1px solid ${t.border}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:8}}>{stars>0&&<span style={{color:t.gold,fontSize:12,letterSpacing:"-1px"}}>{"★".repeat(stars)}</span>}<span style={{fontSize:15,fontWeight:700,color:t.text,fontFamily:FN}}>{name}</span></div><span style={{color:t.muted,fontSize:16}}>{open?"−":"+"}</span></button>{open&&<><PhotoGrid urls={images} t={t}/><div style={{padding:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:16}}><div>{zone&&<div style={{fontSize:13,color:t.muted,marginBottom:4}}>📍 {zone}</div>}{priceNight&&<div style={{display:"flex",alignItems:"baseline",gap:6,marginTop:4}}><span style={{fontSize:28,fontWeight:900,color:t.gold,fontFamily:MN}}>{fmt(parseInt(priceNight))}</span><span style={{fontSize:13,color:t.muted}}>CHF / nuit</span>{priceTotal&&<span style={{fontSize:13,color:t.muted}}>· {fmt(parseInt(priceTotal))} CHF total</span>}</div>}</div>{rating&&<div style={{background:rC,borderRadius:"10px 10px 10px 0",padding:"10px 14px",textAlign:"center",minWidth:56,flexShrink:0}}><div style={{fontSize:20,fontWeight:900,color:"#fff"}}>{rating}</div><div style={{fontSize:9,color:"rgba(255,255,255,0.8)",marginTop:1}}>{rN>=9?"Excellent":rN>=8?"Très bien":"Bien"}</div></div>}</div>{proseLines.length>0&&<p style={{fontSize:13,color:t.muted,lineHeight:1.7,margin:"0 0 16px"}} dangerouslySetInnerHTML={{__html:renderInline(proseLines.join(" ").replace(/\*\*(.+?)\*\*/g,"$1"))}}/>}{chips.length>0&&<div style={{display:"flex",flexWrap:"wrap",gap:6,marginBottom:18}}>{chips.map((c,i)=><span key={i} style={{fontSize:12,color:t.muted,background:t.card,border:`1px solid ${t.border}`,padding:"5px 12px",borderRadius:20}}>✓ {c.label}</span>)}</div>}{bookingLink&&<a href={bookingLink} target="_blank" rel="noopener" style={{display:"inline-block",padding:"12px 22px",background:t.gold,color:"#0a0a0a",borderRadius:10,fontSize:13,fontWeight:700,textDecoration:"none"}}>Réserver ↗</a>}</div></>}</div>);}

function TotauxDisplay({lines,activeClass,t}){const text=lines.join(" ");const totalRow=lines.find(l=>/total/i.test(l)&&l.startsWith("|"));let bT,mT,eT;if(totalRow){const cells=totalRow.split("|").slice(1,-1).map(c=>c.trim().replace(/\s/g,"")).filter(c=>/\d{3,}/.test(c));if(cells.length>=3){bT=cells[0];mT=cells[1];eT=cells[2];}else if(cells.length>=2){bT=cells[0];mT=cells[1];}}const get=p=>{const m=text.match(p);return m?m[1]:null;};if(!bT)bT=get(/(?:Full\s*)?Business[^\d]*(\d[\d\s]{2,})/i);if(!mT)mT=get(/Mixte[^\d]*(\d[\d\s]{2,})/i);if(!eT)eT=get(/[EÉ]co[^\d]*(\d[\d\s]{2,})/i);const fN=v=>{try{return fmt(parseInt((v||"0").replace(/\s/g,"")));}catch{return v||"-";}};
return(<div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginBottom:20}}>{[{id:"business",emoji:"💺",label:"Full Business",total:bT},{id:"mixte",emoji:"🔀",label:"Mixte",total:mT},{id:"eco",emoji:"🪑",label:"Économie",total:eT}].map(c=>{const active=activeClass===c.id;return<div key={c.id} style={{background:active?t.goldBg2:t.card2,border:`2px solid ${active?t.gold:t.border}`,borderRadius:12,padding:"18px 14px",textAlign:"center"}}><div style={{fontSize:11,fontWeight:700,color:active?t.gold:t.muted,marginBottom:8,letterSpacing:"0.06em",fontFamily:FN}}>{c.emoji} {c.label.toUpperCase()}</div><div style={{fontSize:26,fontWeight:900,color:active?t.gold:t.text,fontFamily:MN}}>{c.total?fN(c.total):"-"}</div><div style={{fontSize:11,color:t.muted,marginTop:4}}>CHF</div></div>;})}</div><ProseBlock lines={lines} t={t}/></div>);}

function MeteoDisplay({lines,t}){const[destIdx,setDestIdx]=useState(0);const src=clean(lines.join("\n"));const destBlocks=[];let curBlock={dest:null,lines:[]};for(const l of lines){const dH=l.match(/^\*\*([A-ZÀ-Ÿa-zà-ÿ\s]+[^*]*)\*\*\s*[:\-]/i)||l.match(/^##?\s*([A-ZÀ-Ÿa-zà-ÿ\s]{3,})\s*[\(:]/);if(dH&&destBlocks.length>0){if(curBlock.lines.length>0)destBlocks.push(curBlock);curBlock={dest:dH[1].trim(),lines:[l]};}else curBlock.lines.push(l);}if(curBlock.lines.length>0)destBlocks.push(curBlock);const hasDests=destBlocks.length>1&&destBlocks[0].dest;const activeSrc=hasDests?clean(destBlocks[destIdx].lines.join("\n")):src;const temps=(activeSrc.match(/(\d{1,2})°/g)||[]).map(x=>parseInt(x)).filter(x=>x>0&&x<50);const maxT=temps.length?Math.max(...temps):null;const minT=temps.length>1?Math.min(...temps):null;const seaM=activeSrc.match(/(?:mer|ocean|eau)[^.]*?(\d{1,2})°/i);const seaT=seaM?seaM[1]:null;
return(<div>{hasDests&&<div style={{display:"flex",gap:6,marginBottom:16,flexWrap:"wrap"}}>{destBlocks.map((b,i)=><button key={i} onClick={()=>setDestIdx(i)} style={{padding:"6px 14px",borderRadius:20,border:`1px solid ${i===destIdx?t.gold:t.border}`,background:i===destIdx?t.goldBg2:"transparent",color:i===destIdx?t.gold:t.muted,fontSize:12,cursor:"pointer",fontWeight:i===destIdx?700:400,fontFamily:FN}}>{b.dest||`Dest. ${i+1}`}</button>)}</div>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(90px,1fr))",gap:8,marginBottom:18}}>{maxT&&<div style={{background:t.card2,border:`1px solid ${t.border}`,borderRadius:12,padding:"16px 12px",textAlign:"center"}}><div style={{fontSize:28,marginBottom:6}}>☀️</div><div style={{fontSize:24,fontWeight:900,color:t.gold,fontFamily:MN}}>{maxT}°</div>{minT&&<div style={{fontSize:11,color:t.muted,marginTop:2}}>min {minT}°</div>}<div style={{fontSize:10,color:t.muted,marginTop:3}}>Température</div></div>}{seaT&&<div style={{background:t.card2,border:`1px solid ${t.border}`,borderRadius:12,padding:"16px 12px",textAlign:"center"}}><div style={{fontSize:28,marginBottom:6}}>🌊</div><div style={{fontSize:24,fontWeight:900,color:t.blue,fontFamily:MN}}>{seaT}°</div><div style={{fontSize:10,color:t.muted,marginTop:3}}>Mer</div></div>}<div style={{background:t.card2,border:`1px solid ${t.border}`,borderRadius:12,padding:"16px 12px",textAlign:"center"}}><div style={{fontSize:28,marginBottom:6}}>🌦️</div><div style={{fontSize:13,fontWeight:700,color:t.text}}>{activeSrc.toLowerCase().includes("rare")||activeSrc.toLowerCase().includes("sec")?"Rares":"Modérées"}</div><div style={{fontSize:10,color:t.muted,marginTop:3}}>Précipitations</div></div><div style={{background:t.card2,border:`1px solid ${t.border}`,borderRadius:12,padding:"16px 12px",textAlign:"center"}}><div style={{fontSize:28,marginBottom:6}}>🕶</div><div style={{fontSize:13,fontWeight:700,color:t.text}}>{activeSrc.toLowerCase().includes("élevé")?"Élevé":"Modéré"}</div><div style={{fontSize:10,color:t.muted,marginTop:3}}>UV</div></div></div><ProseBlock lines={hasDests?destBlocks[destIdx].lines:lines} t={t}/></div>);}

function CalendrierDisplay({lines,t}){const entries=[];for(const l of lines){const s=clean(l).trim();if(!s||/^\|[\s:\-|]+\|$/.test(s))continue;const bold=s.match(/^\*\*([^*]+)\*\*\s*[:\-·]\s*(.*)/);if(bold){entries.push({date:bold[1].trim(),activite:bold[2].trim()});continue;}if(s.startsWith("|")){const cells=s.split("|").slice(1,-1).map(c=>c.trim()).filter(c=>c);if(cells.length>=2&&!/^(?:date|jour)/i.test(cells[0])){entries.push({date:cells[0],lieu:cells[1],activite:cells[2]||""});continue;}}const dp=s.match(/^(\d{1,2}(?:\s*[-\/]\s*\d{1,2})?\s+(?:jan|fév|mar|avr|mai|juin|juil|août|sept|oct|nov|déc)[a-z]*(?:\s+\d{4})?)\s*[:\-·]\s*(.*)/i);if(dp){entries.push({date:dp[1].trim(),activite:dp[2].trim()});continue;}const jN=s.match(/^(?:Jour|Day)\s*(\d+)\s*[:\-·]\s*(.*)/i);if(jN)entries.push({date:`Jour ${jN[1]}`,activite:jN[2].trim()});}if(!entries.length)return<ProseBlock lines={lines} t={t}/>;const colors=[t.gold,"#e05555",t.blue,"#9b59b6",t.green];
return(<div style={{position:"relative"}}><div style={{position:"absolute",left:19,top:30,bottom:30,width:2,background:t.border}}/>{entries.map((e,i)=>{const isEnd=i===0||i===entries.length-1;return<div key={i} style={{display:"flex",gap:16,marginBottom:12,position:"relative"}}><div style={{width:40,height:40,borderRadius:"50%",background:isEnd?t.gold:t.card2,border:`2px solid ${isEnd?t.gold:colors[i%colors.length]||t.border}`,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,zIndex:1,marginTop:4}}><span style={{fontSize:14}}>{i===0?"🛫":i===entries.length-1?"🛬":"📍"}</span></div><div style={{flex:1,background:t.card2,border:`1px solid ${isEnd?t.gold:t.border}`,borderRadius:12,padding:"12px 16px"}}><div style={{fontSize:11,fontWeight:800,color:colors[i%colors.length]||t.gold,letterSpacing:"0.06em",marginBottom:3,fontFamily:FN}}>{e.date.toUpperCase()}</div>{e.lieu&&<div style={{fontSize:14,fontWeight:700,color:t.text,marginBottom:2}}>{e.lieu}</div>}{e.activite&&<div style={{fontSize:13,color:t.muted,lineHeight:1.5}} dangerouslySetInnerHTML={{__html:renderInline(e.activite)}}/>}</div></div>;})}</div>);}

function FideliteDisplay({lines,t}){const src=clean(lines.join("\n"));const cleanLines=src.split("\n").filter(l=>l.trim()&&l.trim()!=="|"&&!/^\|[\s:-]+\|/.test(l.trim())).map(l=>l.replace(/^[-•✅]\s*/,"").trim());return(<div style={{display:"flex",flexDirection:"column",gap:8}}>{cleanLines.filter(l=>l.length>5&&!l.startsWith("|")).map((item,i)=><div key={i} style={{background:t.card2,border:`1px solid ${t.border}`,borderRadius:10,padding:"14px 16px",fontSize:13,color:t.muted,lineHeight:1.7}}><span style={{color:t.gold,marginRight:6}}>💳</span><span dangerouslySetInnerHTML={{__html:renderInline(item)}}/></div>)}</div>);}

// ── RESULTS VIEW ──
function ResultsView({text,t}){const[activeClass,setActiveClass]=useState("mixte");const sections=parseSections(text);if(!sections.length)return<ProseBlock lines={text.split("\n")} t={t}/>;const tt=(sections.find(s=>/total|coût/i.test(s.title))?.lines||[]).join(" ");const prices={business:tt.match(/business[^\d]*(\d[\d\s]{2,})/i)?.[1]?.trim()||null,mixte:tt.match(/mixte[^\d]*(\d[\d\s]{2,})/i)?.[1]?.trim()||null,eco:tt.match(/[eé]co[^\d]*(\d[\d\s]{2,})/i)?.[1]?.trim()||null};
return(<div>{sections.map((sec,i)=>{const isRecap=/récap/i.test(sec.title);const isVol=/vols?/i.test(sec.title)&&!/revolut|astuce|fidél/i.test(sec.title);const isHotel=/héberg/i.test(sec.title);const isTotal=/total|coût/i.test(sec.title);const isMeteo=/météo|meteo/i.test(sec.title);const isCal=/calendrier|planning/i.test(sec.title);const isRev=/revolut|astuce|fidél/i.test(sec.title);const hBlocks=isHotel?parseHotelBlocks(sec.lines):[];return(<Sec key={i} title={sec.title} t={t} defaultOpen={isRecap} accent={isTotal}>{isRecap?<RecapDisplay lines={sec.lines} activeClass={activeClass} prices={prices} t={t}/>:isVol?<FlightDisplay lines={sec.lines} activeClass={activeClass} setActiveClass={setActiveClass} prices={prices} t={t}/>:isHotel&&hBlocks.length>0?<div>{hBlocks.map((b,j)=>b.isHeader?<div key={j} style={{padding:"8px 0 12px",fontSize:11,fontWeight:800,letterSpacing:"0.12em",color:t.gold,borderBottom:`1px solid ${t.border}`,marginBottom:14}}>{b.name.toUpperCase()}</div>:<HotelCard key={j} name={b.name} lines={b.lines} t={t}/>)}</div>:isTotal?<TotauxDisplay lines={sec.lines} activeClass={activeClass} t={t}/>:isMeteo?<MeteoDisplay lines={sec.lines} t={t}/>:isCal?<CalendrierDisplay lines={sec.lines} t={t}/>:isRev?<FideliteDisplay lines={sec.lines} t={t}/>:<ProseBlock lines={sec.lines} t={t}/>}</Sec>);})}</div>);}

// ═══════════════════════════════════════════════════════════════
// CHAT WIDGET
// ═══════════════════════════════════════════════════════════════
function ChatWidget({t}){const[open,setOpen]=useState(false);const[msgs,setMsgs]=useState([{role:"assistant",content:"Bonjour ! Posez-moi vos questions sur les vols, hôtels ou activités de votre voyage."}]);const[input,setInput]=useState("");const[loading,setLoading]=useState(false);const endRef=useRef(null);useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[msgs]);
const send=async()=>{if(!input.trim()||loading)return;const userMsg={role:"user",content:input};setMsgs(p=>[...p,userMsg]);setInput("");setLoading(true);try{const res=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[...msgs,userMsg]})});const data=await res.json();setMsgs(p=>[...p,{role:"assistant",content:data.text||"Désolé, je n'ai pas pu répondre."}]);}catch{setMsgs(p=>[...p,{role:"assistant",content:"Erreur de connexion. Réessayez."}]);}setLoading(false);};
if(!open)return<button onClick={()=>setOpen(true)} style={{position:"fixed",bottom:20,right:20,width:52,height:52,borderRadius:"50%",background:t.gold,border:"none",cursor:"pointer",boxShadow:"0 4px 16px rgba(0,0,0,0.3)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22,zIndex:1000,color:"#0a0a0a"}}>💬</button>;
return(<div style={{position:"fixed",bottom:20,right:20,width:360,height:480,background:t.card,border:`1px solid ${t.border}`,borderRadius:16,boxShadow:"0 8px 32px rgba(0,0,0,0.4)",display:"flex",flexDirection:"column",overflow:"hidden",zIndex:1000}}><div style={{padding:"14px 18px",borderBottom:`1px solid ${t.border}`,display:"flex",justifyContent:"space-between",alignItems:"center",background:t.goldBg}}><span style={{fontSize:13,fontWeight:700,color:t.gold,fontFamily:FN}}>💬 Assistant voyage</span><button onClick={()=>setOpen(false)} style={{background:"none",border:"none",color:t.muted,fontSize:18,cursor:"pointer"}}>×</button></div><div style={{flex:1,overflowY:"auto",padding:14,display:"flex",flexDirection:"column",gap:10}}>{msgs.map((m,i)=><div key={i} style={{alignSelf:m.role==="user"?"flex-end":"flex-start",maxWidth:"85%",padding:"10px 14px",borderRadius:m.role==="user"?"14px 14px 4px 14px":"14px 14px 14px 4px",background:m.role==="user"?t.gold:t.card2,color:m.role==="user"?"#0a0a0a":t.text,fontSize:13,lineHeight:1.6,fontFamily:FN}}>{m.content}</div>)}{loading&&<div style={{alignSelf:"flex-start",padding:"10px 14px",borderRadius:14,background:t.card2,color:t.muted,fontSize:13}}>...</div>}<div ref={endRef}/></div><div style={{padding:"10px 14px",borderTop:`1px solid ${t.border}`,display:"flex",gap:8}}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Votre question..." style={{flex:1,padding:"10px 14px",background:t.input,border:`1px solid ${t.border}`,borderRadius:10,color:t.text,fontSize:13,fontFamily:FN,outline:"none"}}/><button onClick={send} disabled={loading} style={{padding:"10px 16px",background:t.gold,border:"none",borderRadius:10,color:"#0a0a0a",fontWeight:700,cursor:"pointer",fontSize:13}}>↑</button></div></div>);}

// ═══════════════════════════════════════════════════════════════
// FORM COMPONENTS
// ═══════════════════════════════════════════════════════════════
function LoyaltySelector({selected,onChange,points,onPoints,t}){return(<div><div style={{display:"flex",flexWrap:"wrap",gap:7,marginBottom:selected.length>0?14:0}}>{LOYALTY.map(p=>{const on=selected.includes(p.id);return<button key={p.id} onClick={()=>onChange(on?selected.filter(x=>x!==p.id):[...selected,p.id])} style={{padding:"6px 13px",borderRadius:20,border:`1px solid ${on?t.gold:t.border}`,background:on?t.goldBg2:"transparent",color:on?t.gold:t.muted,fontSize:11,cursor:"pointer",fontFamily:FN}}>{p.short}</button>;})}</div>{selected.length>0&&<div style={{background:t.card2,borderRadius:10,padding:"14px 16px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><Lbl t={t}>Points disponibles</Lbl><span style={{fontSize:14,fontWeight:800,color:t.gold,fontFamily:MN}}>{points>=100000?">100k":points.toLocaleString("fr-CH")} pts</span></div><input type="range" min="0" max="10" step="1" value={Math.max(0,POINTS_MARKS.findIndex(v=>v===points))} onChange={e=>onPoints(POINTS_MARKS[+e.target.value]||0)} style={{width:"100%",accentColor:t.gold,cursor:"pointer"}}/></div>}</div>);}

function DateFlexCell({value,onChange,flex,onFlexChange,t}){const INP={width:"100%",boxSizing:"border-box",background:t.input,border:`1px solid ${t.border}`,borderRadius:10,color:t.text,fontSize:14,fontFamily:FN,padding:"13px 16px",outline:"none"};return(<div><input type="date" value={value} onChange={e=>onChange(e.target.value)} style={INP}/><div style={{display:"flex",alignItems:"center",marginTop:5,gap:5}}><button onClick={()=>onFlexChange(0)} style={{fontSize:9,fontWeight:700,padding:"3px 7px",borderRadius:10,border:`1px solid ${flex===0?t.gold:t.border}`,background:flex===0?t.goldBg2:"transparent",color:flex===0?t.gold:t.muted,cursor:"pointer",letterSpacing:"0.05em",whiteSpace:"nowrap"}}>EXACT</button><button onClick={()=>onFlexChange(flex===0?3:flex)} style={{fontSize:9,fontWeight:700,padding:"3px 7px",borderRadius:10,border:`1px solid ${flex>0?t.gold:t.border}`,background:flex>0?t.goldBg2:"transparent",color:flex>0?t.gold:t.muted,cursor:"pointer",letterSpacing:"0.05em",whiteSpace:"nowrap"}}>{flex>0?`± ${flex}j`:"± JOURS"}</button></div>{flex>0&&<div style={{marginTop:7,padding:"10px 12px",background:t.card2,borderRadius:8}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:10,color:t.muted,letterSpacing:"0.06em"}}>FLEXIBILITÉ</span><span style={{fontSize:12,fontWeight:800,color:t.gold,fontFamily:MN}}>± {flex}j</span></div><input type="range" min="1" max="21" step="1" value={flex} onChange={e=>onFlexChange(+e.target.value)} style={{width:"100%",accentColor:t.gold,cursor:"pointer"}}/></div>}</div>);}

// ═══════════════════════════════════════════════════════════════
// MAIN APP
// ═══════════════════════════════════════════════════════════════
export default function App(){
  const[isDark,setIsDark]=useState(true);const t=isDark?DARK:LIGHT;
  useEffect(()=>{document.body.style.background=t.bg;document.body.style.margin="0";document.documentElement.style.background=t.bg;},[t.bg]);
  const[activeTab,setActiveTab]=useState("trips");
  const[loyaltyCards,setLoyaltyCards]=useState([]);const[loyaltyPoints,setLoyaltyPoints]=useState(0);
  const[from,setFrom]=useState("GVA");const[fromCustom,setFromCustom]=useState("");
  const[legs,setLegs]=useState([{to:"",depDate:"",retDate:"",depFlex:0,retFlex:0}]);
  const[travelers,setTravelers]=useState("1");const[baggage,setBaggage]=useState("no_pref");
  const[vibes,setVibes]=useState([]);const[activities,setActivities]=useState([]);const[notes,setNotes]=useState("");
  const[phase,setPhase]=useState("idle");const[result,setResult]=useState("");const[err,setErr]=useState("");const[tipIdx,setTipIdx]=useState(0);
  const timer=useRef(null);
  useEffect(()=>{if(phase==="loading")timer.current=setInterval(()=>setTipIdx(i=>(i+1)%TIPS.length),2800);else{clearInterval(timer.current);setTipIdx(0);}return()=>clearInterval(timer.current);},[phase]);
  const addLeg=()=>{if(legs.length<5)setLegs(l=>[...l,{to:"",depDate:l[l.length-1].retDate||"",retDate:"",depFlex:0,retFlex:0}]);};
  const removeLeg=idx=>setLegs(l=>l.filter((_,i)=>i!==idx));
  const updateLeg=(idx,field,val)=>{setLegs(l=>{const n=l.map((leg,i)=>i===idx?{...leg,[field]:val}:leg);if(field==="retDate"&&idx+1<n.length)n[idx+1]={...n[idx+1],depDate:val};return n;});};
  const toggleVibe=id=>setVibes(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  const toggleAct=id=>setActivities(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]);
  const INP={width:"100%",boxSizing:"border-box",background:t.input,border:`1px solid ${t.border}`,borderRadius:10,color:t.text,fontSize:14,fontFamily:FN,padding:"13px 16px",outline:"none",WebkitAppearance:"none",appearance:"none"};
  const INP_RO={...INP,color:t.muted,cursor:"default",background:t.card2};

  const buildPrompt=()=>{const airport=from==="OTHER"?fromCustom.toUpperCase():from;const vibeLabels=VIBES.filter(v=>vibes.includes(v.id)).map(v=>v.label).join(", ");const actLabels=ACTIVITIES.filter(a=>activities.includes(a.id)).map(a=>a.label).join(", ");const legLines=legs.filter(l=>l.to).map((l,i)=>{const fp=i===0?airport:(legs[i-1].to||airport);const parts=[`Vol ${i+1} : ${fp} -> ${l.to}`];if(l.depDate)parts.push(`départ ${l.depDate}${l.depFlex>0?` (flexible ±${l.depFlex} jours)`:""}`);if(l.retDate)parts.push(i===legs.length-1?`retour ${l.retDate}${l.retFlex>0?` (flexible ±${l.retFlex} jours)`:""}`:`arrivée ${l.retDate}${l.retFlex>0?` (flexible ±${l.retFlex} jours)`:""}`);return"✈️ "+parts.join(" - ");});const bagLabel=BAGGAGE_OPTIONS.find(b=>b.id===baggage)?.label||"";const loyaltyInfo=loyaltyCards.length>0?`🎫 Programmes : ${loyaltyCards.map(id=>LOYALTY.find(p=>p.id===id)?.short).join(", ")} - ${loyaltyPoints>=100000?">100k":loyaltyPoints.toLocaleString("fr-CH")} pts`:"";return["Planifie ce voyage, recherche tous les prix en temps réel. Utiliser uniquement le tiret simple ( - ) :",`Aéroport de base : ${airport}`,...legLines,`Voyageurs : ${travelers}`,baggage!=="no_pref"?`Bagages : ${bagLabel}`:"",loyaltyInfo,vibeLabels?`Ambiance : ${vibeLabels}`:"",actLabels?`Activités : ${actLabels}`:"",notes?`Notes : ${notes}`:"","","Pour chaque hôtel : effectuer une recherche web pour trouver les URLs directes des photos (.jpg/.webp) depuis le CDN Booking.com ou site officiel. Inclure : IMAGES: url1.jpg | url2.jpg | url3.jpg. Tableau complet, 3 scénarios de classe, totaux CHF, liens Booking/Kayak."].filter(Boolean).join("\n");};
  const go=async()=>{if(!legs[0].to||!legs[0].depDate){setErr("Au minimum : une destination et une date de départ.");return;}if(from==="OTHER"&&!fromCustom.trim()){setErr("Merci d'entrer le code IATA.");return;}setPhase("loading");setErr("");setResult("");try{const res=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:buildPrompt()}]})});const data=await res.json();if(!res.ok||data.error)throw new Error(data.error||`Erreur ${res.status}`);setResult(data.text||"Aucun résultat.");setPhase("done");}catch(e){setErr(e.message);setPhase("error");}};
  const reset=()=>{setPhase("idle");setResult("");setErr("");};

  return(
    <div style={{maxWidth:900,margin:"0 auto",padding:"2rem 1.5rem",background:t.bg,minHeight:"100vh",fontFamily:FN,transition:"background 0.3s"}}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,600;0,700&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet"/>

      {/* Theme toggle */}
      <div style={{position:"fixed",top:16,right:16,zIndex:1001}}>
        <button onClick={()=>setIsDark(!isDark)} style={{width:40,height:40,borderRadius:"50%",border:`1px solid ${t.border}`,background:t.card,color:t.gold,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:"0 2px 8px rgba(0,0,0,0.2)",transition:"all 0.3s",fontSize:16}}>{isDark?"☀️":"🌙"}</button>
      </div>

      {/* Header */}
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24}}>
        <div><div style={{fontSize:36,fontWeight:900,letterSpacing:"-0.04em",color:t.text,lineHeight:1}}>WDC</div><div style={{fontSize:11,fontWeight:700,letterSpacing:"0.18em",color:t.gold,marginTop:1}}>AI TRAVEL</div></div>
        <div style={{fontSize:10,color:t.muted,textAlign:"right",lineHeight:1.9,marginTop:4}}><div>GVA - ZRH - MXP</div><div>CHF - 4★ - 8+/10</div></div>
      </div>

      {phase!=="done"&&<>
        {/* Nav tabs */}
        <div style={{display:"flex",gap:8,marginBottom:20}}>{[{id:"trips",label:"🗺 Trips"},{id:"vols",label:"✈️ Vols"},{id:"hotels",label:"🏨 Hébergements"}].map(tab=><button key={tab.id} onClick={()=>setActiveTab(tab.id)} style={{padding:"9px 18px",borderRadius:20,border:`1px solid ${activeTab===tab.id?t.gold:t.border}`,background:activeTab===tab.id?t.gold:"transparent",color:activeTab===tab.id?"#0a0a0a":t.muted,fontSize:12,fontWeight:activeTab===tab.id?700:500,cursor:"pointer",letterSpacing:"0.05em",fontFamily:FN}}>{tab.label}</button>)}</div>

        {/* Loyalty */}
        <div style={{background:t.card,border:`1px solid ${t.border}`,borderRadius:14,padding:"18px 22px",marginBottom:10}}><Lbl t={t}>Programmes de fidélité</Lbl><LoyaltySelector selected={loyaltyCards} onChange={setLoyaltyCards} points={loyaltyPoints} onPoints={setLoyaltyPoints} t={t}/></div>

        {/* Search form */}
        <div style={{background:t.card,border:`1px solid ${t.border}`,borderRadius:16,overflow:"hidden",marginBottom:10}}>
          <div style={{padding:"20px 24px",borderBottom:`1px solid ${t.border}`,display:"grid",gridTemplateColumns:"1fr 1.5fr",gap:16}}>
            <div><Lbl t={t}>Voyageurs</Lbl><select value={travelers} onChange={e=>setTravelers(e.target.value)} style={INP}>{[1,2,3,4,5,6,8,10].map(n=><option key={n} value={n}>{String(n).padStart(2,"0")} - {n===1?"personne":"personnes"}</option>)}</select></div>
            <div><Lbl t={t}>Bagages</Lbl><select value={baggage} onChange={e=>setBaggage(e.target.value)} style={INP}>{BAGGAGE_OPTIONS.map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select></div>
          </div>
          {from==="OTHER"&&<div style={{padding:"14px 24px 0"}}><input value={fromCustom} onChange={e=>setFromCustom(e.target.value.toUpperCase())} placeholder="Code IATA - ex: LYS, NTE, ORY..." maxLength={4} style={{...INP,width:200,fontFamily:"monospace",letterSpacing:"0.12em"}}/></div>}
          <div style={{padding:"20px 24px 8px"}}>
            <div style={{display:"grid",gridTemplateColumns:"minmax(0,1.2fr) 20px minmax(0,1.5fr) minmax(0,1fr) minmax(0,1fr) 36px",gap:8,marginBottom:8}}>
              <Lbl t={t}>Depuis</Lbl><div/><Lbl t={t}>Vers</Lbl><Lbl t={t}>Date aller</Lbl><Lbl t={t}>Date retour</Lbl><div/>
            </div>
            {legs.map((leg,idx)=>(
              <div key={idx} style={{display:"grid",gridTemplateColumns:"minmax(0,1.2fr) 20px minmax(0,1.5fr) minmax(0,1fr) minmax(0,1fr) 36px",gap:8,alignItems:"flex-start",marginBottom:8}}>
                {idx===0?<select value={from} onChange={e=>setFrom(e.target.value)} style={INP}>{AIRPORTS.map(a=><option key={a.code} value={a.code}>{a.code==="OTHER"?"✏ Autre":`${a.code} - ${a.name}`}</option>)}</select>:<div style={{...INP_RO,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{legs[idx-1].to||"-"}</div>}
                <div style={{textAlign:"center",color:t.gold,fontWeight:900,fontSize:16,paddingTop:13}}>→</div>
                <input value={leg.to} onChange={e=>updateLeg(idx,"to",e.target.value)} placeholder={["Marbella, Espagne","Chicago, USA","Costa Rica"][idx]||"Destination"} style={INP}/>
                <DateFlexCell value={leg.depDate} onChange={v=>updateLeg(idx,"depDate",v)} flex={leg.depFlex||0} onFlexChange={v=>updateLeg(idx,"depFlex",v)} t={t}/>
                <DateFlexCell value={leg.retDate} onChange={v=>updateLeg(idx,"retDate",v)} flex={leg.retFlex||0} onFlexChange={v=>updateLeg(idx,"retFlex",v)} t={t}/>
                {idx>0?<button onClick={()=>removeLeg(idx)} style={{width:36,height:36,border:`1px solid ${t.border}`,background:"transparent",cursor:"pointer",color:t.muted,fontSize:18,display:"flex",alignItems:"center",justifyContent:"center",borderRadius:8}}>×</button>:<div/>}
              </div>
            ))}
            {legs.length<5&&<button onClick={addLeg} style={{fontSize:11,padding:"7px 16px",border:`1px dashed ${t.border}`,background:"transparent",cursor:"pointer",color:t.muted,borderRadius:8,marginTop:4,marginBottom:8,fontFamily:FN}}>+ Ajouter une étape ({legs.length}/5)</button>}
          </div>
          <div style={{borderTop:`1px solid ${t.border}`}}/>
          <div style={{padding:"20px 24px 14px"}}><Lbl t={t}>Ambiance</Lbl><div style={{display:"flex",flexWrap:"wrap",gap:7}}>{VIBES.map(v=><ChipBtn key={v.id} label={v.label} selected={vibes.includes(v.id)} onClick={()=>toggleVibe(v.id)} t={t}/>)}</div></div>
          <div style={{padding:"0 24px 14px"}}><Lbl t={t}>Activités</Lbl><div style={{display:"flex",flexWrap:"wrap",gap:7}}>{ACTIVITIES.map(a=><ChipBtn key={a.id} label={a.label} selected={activities.includes(a.id)} onClick={()=>toggleAct(a.id)} t={t}/>)}</div></div>
          <div style={{padding:"0 24px 20px"}}><Lbl t={t}>Notes spécifiques</Lbl><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Budget max, occasion spéciale, compagnie préférée..." style={{...INP,minHeight:52,resize:"vertical"}}/></div>
          {err&&<div style={{margin:"0 24px 16px",fontSize:13,color:"#ff7070",background:"rgba(255,100,100,0.1)",border:"1px solid rgba(255,100,100,0.25)",borderRadius:8,padding:"10px 14px"}}>⚠ {err}</div>}
          <div style={{padding:"0 24px 24px"}}><button onClick={go} disabled={phase==="loading"} style={{width:"100%",padding:16,background:phase==="loading"?t.faint:`linear-gradient(135deg,${t.gold},#d4b85c)`,color:phase==="loading"?t.muted:"#0a0a0a",border:"none",borderRadius:12,cursor:phase==="loading"?"not-allowed":"pointer",fontSize:12,fontWeight:800,letterSpacing:"0.18em",fontFamily:FN}}>{phase==="loading"?"RECHERCHE EN COURS...":"LANCER LA RECHERCHE"}</button></div>
        </div>
      </>}

      {/* Loading */}
      {phase==="loading"&&<div style={{background:t.card,border:`1px solid ${t.border}`,borderRadius:16,padding:"3rem",textAlign:"center",marginTop:10}}><div style={{fontSize:44,marginBottom:"1rem"}}>✈️</div><div style={{fontSize:11,fontWeight:800,letterSpacing:"0.14em",color:t.text,marginBottom:8,fontFamily:FN}}>{TIPS[tipIdx].toUpperCase()}</div><div style={{fontSize:10,color:t.muted,fontFamily:MN,letterSpacing:"0.08em"}}>KAYAK · BOOKING · GOOGLE FLIGHTS · SKYSCANNER</div><div style={{display:"flex",justifyContent:"center",gap:6,marginTop:"1.5rem"}}>{TIPS.map((_,i)=><div key={i} style={{width:5,height:5,borderRadius:"50%",background:i===tipIdx?t.gold:t.border}}/>)}</div></div>}

      {/* Results */}
      {phase==="done"&&result&&<div style={{marginTop:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={{display:"flex",alignItems:"baseline",gap:12}}><span style={{fontSize:11,fontWeight:800,letterSpacing:"0.14em",color:t.text,fontFamily:FN}}>RÉSULTATS</span><span style={{fontSize:10,color:t.muted}}>{new Date().toLocaleDateString("fr-CH",{day:"numeric",month:"long",year:"numeric"})}</span></div><div style={{display:"flex",gap:8}}><button onClick={()=>navigator.clipboard?.writeText(result)} style={{fontSize:10,fontWeight:700,letterSpacing:"0.08em",padding:"6px 14px",background:"transparent",border:`1px solid ${t.border}`,borderRadius:6,cursor:"pointer",color:t.muted,fontFamily:FN}}>COPIER</button><button onClick={reset} style={{fontSize:10,fontWeight:700,letterSpacing:"0.08em",padding:"6px 14px",background:t.gold,border:"none",borderRadius:6,cursor:"pointer",color:"#0a0a0a",fontFamily:FN}}>NOUVELLE RECHERCHE</button></div></div><ResultsView text={result} t={t}/></div>}

      <div style={{marginTop:24,textAlign:"center",fontSize:10,color:t.faint,letterSpacing:"0.1em",fontFamily:MN}}>KAYAK · BOOKING · AIRBNB · GOOGLE FLIGHTS · SKYSCANNER · MOMONDO · EXPEDIA · OPODO</div>

      {/* Chat widget */}
      <ChatWidget t={t}/>
    </div>
  );
}
